name: Deploy to EC2

on:
  push:
    branches:
      - main  # Or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION_ID }}

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Install Nginx (if not already installed)
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_PRIVATE_IP }} 'sudo apt-get update && sudo apt-get install -y nginx'

    - name: Copy webpage.html to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa webpage.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_PRIVATE_IP }}:/var/www/html/webpage.html

    - name: Restart Nginx on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_PRIVATE_IP }} 'sudo systemctl restart nginx'
